server:
  servlet:
    context-path: /stomp-engine
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
        # generate_statistics: true
        jdbc:
          time_zone: UTC
    show-sql: true
  liquibase:
    change-log: classpath:releases/migrations.xml
    contexts: local
  datasource:
    url: jdbc:mysql://localhost:3306/stomp_league
    username: root
    password: WindyKayak@3
  mvc:
    pathmatch:
      # To prevent "Failed to start bean 'documentationPluginsBootstrapper'" exception
      matching-strategy: ANT_PATH_MATCHER

springdoc:
  swagger-ui:
    enabled: true

logging:
  level:
    liquibase: DEBUG
